/**
 * Decision Persistence & Deduplication
 *
 * Persists decisions generated by runCopilot() to the copilot_decisions table.
 * Uses content hashing for deduplication — if the same decision (category + title + instruction)
 * is generated again, the existing record is kept instead of creating a duplicate.
 *
 * This enables:
 *   - Decision-to-action linking (prevents duplicate actions)
 *   - Outcome tracking over time
 *   - Historical analysis of what the system recommended
 */

import { createServerClient } from "@/lib/supabase/server";
import type { GMDecision } from "./types";
import { createHash } from "crypto";

const DEFAULT_SITE_ID = "00000000-0000-0000-0000-000000000001";

// Decision expires after 18 hours (covers a full service day)
const DECISION_TTL_HOURS = 18;

/**
 * Generate a stable hash for a decision based on its core identity.
 * Two decisions with the same category + title pattern will hash the same,
 * preventing duplicates within the same service day.
 */
export function hashDecision(d: GMDecision): string {
  // Normalize: strip numbers/amounts from title to group similar decisions
  const normalizedTitle = d.title
    .replace(/R[\d,.\s]+/g, "R_AMT")    // R 5,200 → R_AMT
    .replace(/\d+(\.\d+)?%/g, "_PCT")    // 34.2% → _PCT
    .replace(/\d+/g, "_N");              // other numbers

  const content = `${d.category}|${normalizedTitle}|${d.actionType}`;
  return createHash("sha256").update(content).digest("hex").slice(0, 16);
}

/**
 * Persist a batch of decisions. Deduplicates against existing active decisions
 * for the same site. Returns the persisted decision IDs mapped by original decision ID.
 */
export async function persistDecisions(
  decisions: GMDecision[],
  siteId: string = DEFAULT_SITE_ID,
): Promise<Map<string, string>> {
  const supabase = createServerClient();
  const idMap = new Map<string, string>(); // originalId → persistedId

  if (decisions.length === 0) return idMap;

  // 1. Hash all incoming decisions
  const hashes = decisions.map((d) => hashDecision(d));

  // 2. Find existing active decisions with matching hashes
  const { data: existing } = await (supabase.from("copilot_decisions" as any) as any)
    .select("id, decision_hash")
    .eq("site_id", siteId)
    .eq("status", "active")
    .in("decision_hash", hashes);

  const existingByHash = new Map<string, string>();
  for (const row of (existing ?? []) as { id: string; decision_hash: string }[]) {
    existingByHash.set(row.decision_hash, row.id);
  }

  // 3. Upsert: skip existing, insert new
  const expiresAt = new Date(Date.now() + DECISION_TTL_HOURS * 60 * 60 * 1000).toISOString();
  const toInsert: Record<string, unknown>[] = [];

  for (let i = 0; i < decisions.length; i++) {
    const d = decisions[i];
    const hash = hashes[i];

    if (existingByHash.has(hash)) {
      // Decision already exists — reuse its ID
      idMap.set(d.id, existingByHash.get(hash)!);
    } else {
      const row = {
        site_id: siteId,
        decision_hash: hash,
        category: d.category,
        severity: d.severity,
        title: d.title,
        direct_instruction: d.directInstruction,
        why_it_matters: d.whyItMatters,
        expected_impact_text: d.expectedImpactText,
        expected_impact_value: d.expectedImpactValue,
        owner: d.owner,
        due_at: d.dueAt,
        service_window: d.serviceWindowRelevance,
        confidence_type: d.confidenceType,
        status: "active",
        expires_at: expiresAt,
      };
      toInsert.push(row);
    }
  }

  if (toInsert.length > 0) {
    const { data: inserted } = await (supabase.from("copilot_decisions" as any) as any)
      .insert(toInsert)
      .select("id, decision_hash");

    // Map inserted decision hashes back to original IDs
    const insertedByHash = new Map<string, string>();
    for (const row of (inserted ?? []) as { id: string; decision_hash: string }[]) {
      insertedByHash.set(row.decision_hash, row.id);
    }

    for (let i = 0; i < decisions.length; i++) {
      const d = decisions[i];
      const hash = hashes[i];
      if (!idMap.has(d.id) && insertedByHash.has(hash)) {
        idMap.set(d.id, insertedByHash.get(hash)!);
      }
    }
  }

  return idMap;
}

/**
 * Check if an action already exists for a given decision.
 * Used to prevent double-creation when a GM clicks "Start" on a decision
 * that was already actioned.
 */
export async function getExistingActionForDecision(
  decisionId: string,
): Promise<string | null> {
  const supabase = createServerClient();
  const { data } = await (supabase.from("copilot_decisions" as any) as any)
    .select("action_id")
    .eq("id", decisionId)
    .eq("status", "actioned")
    .maybeSingle();

  return (data as { action_id: string | null } | null)?.action_id ?? null;
}

/**
 * Link a decision to an action (when "Start" is clicked).
 */
export async function linkDecisionToAction(
  decisionId: string,
  actionId: string,
): Promise<void> {
  const supabase = createServerClient();
  await (supabase.from("copilot_decisions" as any) as any)
    .update({ status: "actioned", action_id: actionId })
    .eq("id", decisionId);
}

/**
 * Apply persisted action statuses to a fresh set of generated decisions.
 * Matches by content hash — if a decision was previously actioned, its
 * status is restored so the UI shows the correct state on page load.
 */
export async function applyActionedStatuses(
  decisions: GMDecision[],
  siteId: string = DEFAULT_SITE_ID,
): Promise<GMDecision[]> {
  const statusMap = await getActionedDecisionStatuses(siteId);
  if (statusMap.size === 0) return decisions;
  return decisions.map((d) => {
    const hash = hashDecision(d);
    const status = statusMap.get(hash);
    return status ? { ...d, status } : d;
  });
}

/**
 * Load the action statuses for decisions that have been actioned today.
 * Returns a map of decision_hash → action status, so the orchestrator can
 * mark decisions as "in_progress" / "completed" / "escalated" on page load.
 */
export async function getActionedDecisionStatuses(
  siteId: string = DEFAULT_SITE_ID,
): Promise<Map<string, "pending" | "in_progress" | "completed" | "escalated">> {
  const supabase = createServerClient();
  const { data } = await (supabase.from("copilot_decisions" as any) as any)
    .select("decision_hash, action_id")
    .eq("site_id", siteId)
    .eq("status", "actioned")
    .not("action_id", "is", null);

  const result = new Map<string, "pending" | "in_progress" | "completed" | "escalated">();
  if (!data || (data as any[]).length === 0) return result;

  const actionIds = (data as { decision_hash: string; action_id: string }[])
    .map((r) => r.action_id);

  const { data: actionRows } = await supabase
    .from("actions")
    .select("id, status")
    .in("id", actionIds);

  const actionStatusById = new Map<string, string>();
  for (const row of (actionRows ?? []) as { id: string; status: string }[]) {
    actionStatusById.set(row.id, row.status);
  }

  for (const row of data as { decision_hash: string; action_id: string }[]) {
    const status = actionStatusById.get(row.action_id);
    if (status) {
      result.set(
        row.decision_hash,
        status as "pending" | "in_progress" | "completed" | "escalated",
      );
    }
  }

  return result;
}

/**
 * Expire stale decisions (called periodically or at end of day).
 */
export async function expireStaleDecisions(
  siteId: string = DEFAULT_SITE_ID,
): Promise<number> {
  const supabase = createServerClient();
  const { data } = await (supabase.from("copilot_decisions" as any) as any)
    .update({ status: "expired" })
    .eq("site_id", siteId)
    .eq("status", "active")
    .lt("expires_at", new Date().toISOString())
    .select("id");

  return (data as unknown[] | null)?.length ?? 0;
}

/**
 * Supersede old active decisions when new ones replace them.
 * Called after inserting new decisions for a fresh copilot run.
 */
export async function supersedeOldDecisions(
  siteId: string,
  currentHashes: string[],
): Promise<void> {
  if (currentHashes.length === 0) return;

  const supabase = createServerClient();
  // Mark any active decision whose hash is NOT in the current set as superseded
  // This is done in a single update: active decisions for the site that don't match current hashes
  const { data: active } = await (supabase.from("copilot_decisions" as any) as any)
    .select("id, decision_hash")
    .eq("site_id", siteId)
    .eq("status", "active");

  const toSupersede = ((active ?? []) as { id: string; decision_hash: string }[])
    .filter((row) => !currentHashes.includes(row.decision_hash))
    .map((row) => row.id);

  if (toSupersede.length > 0) {
    await (supabase.from("copilot_decisions" as any) as any)
      .update({ status: "superseded", superseded_at: new Date().toISOString() })
      .in("id", toSupersede);
  }
}
