-- ============================================================
-- Ops Engine — Automated Operational Alerts Engine
-- Migration: 008_alerts_engine.sql
--
-- Persisted alerts generated by the background alerts engine.
-- One row per alert event; resolved via the UI or API.
-- ============================================================

create table if not exists alerts (
  id              uuid        primary key default gen_random_uuid(),
  alert_type      text        not null,
  location        text,
  severity        text        not null check (severity in ('low','medium','high','critical')),
  message         text        not null,
  recommendation  text,
  resolved        boolean     not null default false,
  resolved_at     timestamptz,
  created_at      timestamptz not null default now()
);

-- Lookup active (unresolved) alerts fast
create index if not exists idx_alerts_resolved_severity
  on alerts (resolved, severity, created_at desc);

-- Lookup by type (de-duplication check)
create index if not exists idx_alerts_type_created
  on alerts (alert_type, created_at desc);
