-- ============================================================
-- SUPERSEDED — DO NOT EDIT
-- This file was a duplicate of migration 032 (alongside 032_actions_upgrade.sql).
-- Its content has been moved to 097_add_par_level.sql.
-- This stub is intentionally a no-op so Supabase does not re-run the migration.
-- ============================================================
