-- ============================================================
-- Enterprise Hardening
-- Migration: 038_enterprise_hardening.sql
--
-- 1. Add operational config columns to sites table
-- 2. Create copilot_decisions table for decision persistence
-- 3. Create copilot_decision_actions link table
-- ============================================================

-- ── 1. Site-level operational config ──────────────────────────────────────────
-- Move hardcoded constants into per-site configuration

ALTER TABLE sites
  ADD COLUMN IF NOT EXISTS target_avg_spend     numeric(8,2)  DEFAULT 280.0,
  ADD COLUMN IF NOT EXISTS seating_capacity     integer       DEFAULT 200,
  ADD COLUMN IF NOT EXISTS currency_symbol      text          DEFAULT 'R',
  ADD COLUMN IF NOT EXISTS timezone             text          DEFAULT 'Africa/Johannesburg';

-- Ensure target_labour_pct exists (migration 022 added it but confirm default)
ALTER TABLE sites ALTER COLUMN target_labour_pct SET DEFAULT 30.0;

-- ── 2. Copilot decisions — persistence layer ─────────────────────────────────
-- Decisions generated by runCopilot() are persisted here instead of being ephemeral.
-- This enables deduplication, outcome tracking, and historical analysis.

CREATE TABLE IF NOT EXISTS copilot_decisions (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id             uuid        NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  decision_hash       text        NOT NULL,
  category            text        NOT NULL,
  severity            text        NOT NULL,
  title               text        NOT NULL,
  direct_instruction  text,
  why_it_matters      text,
  expected_impact_text text,
  expected_impact_value numeric(12,2),
  owner               text,
  due_at              text,
  service_window      text,
  confidence_type     text,
  status              text        NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'superseded', 'actioned', 'dismissed', 'expired')),
  action_id           uuid        REFERENCES actions(id) ON DELETE SET NULL,
  generated_at        timestamptz NOT NULL DEFAULT now(),
  expires_at          timestamptz,
  superseded_at       timestamptz
);

-- Fast lookups: active decisions per site, hash dedup
CREATE INDEX IF NOT EXISTS idx_copilot_decisions_site_active
  ON copilot_decisions (site_id, status, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_copilot_decisions_hash
  ON copilot_decisions (site_id, decision_hash, status);

-- RLS
ALTER TABLE copilot_decisions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated_all" ON copilot_decisions;
CREATE POLICY "authenticated_all" ON copilot_decisions
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "service_role_all" ON copilot_decisions;
CREATE POLICY "service_role_all" ON copilot_decisions
  FOR ALL TO service_role USING (true) WITH CHECK (true);
