-- ============================================================
-- SUPERSEDED — DO NOT EDIT
-- This file was a duplicate of migration 043 (alongside 043_user_roles_bootstrap.sql
-- and 043_menu_item_food_cost.sql).
-- Its content has been moved to 098_add_site_id_to_sales_uploads.sql.
-- This stub is intentionally a no-op so Supabase does not re-run the migration.
-- ============================================================
